### ISSUE TITLE
Conditional Patching Needed To Ensure Compatibility

### ISSUE THREAD

**Issue by Jdalt40** [firefoxpdm/Researchable-Stat-Upgrades#1]
You miiight want to implement safe patching with your xpath using conditional checking. Your patching doesn't check for other mods that have patched the same values, such as Harvest Yield Patch (comes into play if loaded AFTER HYP due to them using conditional checking).

**Comment by firefoxpdm** [comment]
I will have a look at it. Please note that this is how the original author created the patches, so far I only changed what I had to to make it strictly 1.1 compatible.

**Comment by firefoxpdm** [comment]
Added the \<success\> tags to ensure that the patching doesn't fail on the removed elements.
