### ISSUE TITLE
Semi-Incompatibility with RPG Style Level Up Mod

### ISSUE THREAD

**Issue by CMDRYouth** [firefoxpdm/Researchable-Stat-Upgrades#2]
https://steamcommunity.com/sharedfiles/filedetails/?id=1995668415

Is it possible to identify the incompatibilities between these two mods? I have been using the RPG Stats for a while now and was glad to see Researchable Stat Upgrades reuploaded to 1.1, having enjoyed it thoroughly in 1.0, though it seems the two mods don't play very nicely with each other. Bonuses are overwriting each other in certain places, and benefits you could normally gain from one are being supplanted/removed/changed by the effects of the other.

As far as I can tell, these nitpicks aren't showing up in the debug log.

**Comment by CMDRYouth** [comment]
Actually I think this somehow resolved itself.  It was probably the mod load order.  Apologies.

**Comment by firefoxpdm** [comment]
I will try and have a look at it. Which mod load order seems to be the correct one?

**Comment by CMDRYouth** [comment]
Sorry for taking so long to reply.  I hadn’t checked my email in a few
weeks and there was a bunch of things piled up.  I also wasn’t too aware on
how github messages worked, so this email is a surprise to me.

Stat Upgrades loading first and then RPG Stats afterwards seems to be the
correct order, assumably to let factors from research apply first, then for
the additional boosts from pawn stats to be added.  Doing it the other way
around causes factor from research to “overwrite” some of the other boosts
otherwise.

**Comment by firefoxpdm** [comment]
No problem, we are not in a hurry.

I went through the RPG mod and have identified a couple problems with how the patching was being done by this one, so I ended up reworking all of it. Now it should be working fine, regardless of the loading order, and hopefully it will prevent future issues to pop up as well.
