### ISSUE TITLE
Mining error

### ISSUE THREAD

**Issue by jjanow** [firefoxpdm/Researchable-Stat-Upgrades#3]
I am getting this red error when I load the mod, regardless of where I place it in the load order:
```
XML RimWorld.StatDef defines the same field twice: parts.

Field contents: AdvMiningIII1.075AdvMiningIV1.1.

Whole XML:

<StatDef><defName>MiningYield</defName><label>mining yield</label><description>The percentage of mined resources a miner will produce.\n\nThis applies to both wall mining and deep drill mining.\nThis doesn't affect the production rate of rock chunks.</description><category>PawnWork</category><defaultBaseValue>1</defaultBaseValue><minValue>0</minValue><maxValue>9999999</maxValue><toStringStyle>PercentZero</toStringStyle><skillNeedFactors><li Class="SkillNeed_Direct"><skill>Mining</skill><valuesPerLevel><li>0.6</li><li>0.7</li><li>0.8</li><li>0.85</li><li>0.9</li><li>0.925</li><li>0.95</li><li>0.975</li><li>1</li><li>1.01</li><li>1.02</li><li>1.03</li><li>1.04</li><li>1.05</li><li>1.06</li><li>1.07</li><li>1.08</li><li>1.09</li><li>1.10</li><li>1.12</li><li>1.13</li></valuesPerLevel></li></skillNeedFactors><capacityFactors><li><capacity>Manipulation</capacity><weight>0.3</weight><max>1</max></li><li><capacity>Sight</capacity><weight>0.2</weight><max>1</max></li></capacityFactors><parts><li Class="StatPart_Difficulty_MiningYield" /></parts><displayPriorityInCategory>4901</displayPriorityInCategory><parts><li Class="ResearchableStatUpgrades.StatPart_ResearchDependent"><researchFactors><li><def>AdvMiningIII</def><factor>1.075</factor></li><li><def>AdvMiningIV</def><factor>1.1</factor></li></researchFactors></li></parts></StatDef>
Verse.Log:Error(String, Boolean)
Verse.DirectXmlToObject:ObjectFromXml(XmlNode, Boolean)
Verse.DirectXmlToObject:ObjectFromXmlReflection(XmlNode, Boolean)
Verse.DirectXmlLoader:DefFromNode(XmlNode, LoadableXmlAsset)
Verse.LoadedModManager:ParseAndProcessXML(XmlDocument, Dictionary`2)
Verse.LoadedModManager:LoadAllActiveMods()
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.<>c:<Start>b__6_1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()
```

**Comment by firefoxpdm** [comment]
Are you using the steam version of the mod, or the release version from here?
If you are using the steam one, can you please take the one from here and check if you can reproduce the issue with that version as well?
If you can reproduce the issue with this release version as well, can you please check if it happens also if only this mod is loaded?
If it doesn't happen when only this mod is loaded, could you try and find out which other mod is interfering with it?

If none of the above yield any usable results, could you please give me step-by-step instructions on how to reproduce the error, using only this mod and a new save game?

**Comment by jjanow** [comment]
I was originally using the Steam version, but installed the Git version for testing.  Both versions generate the same error.
I stripped it down to Harmony, Core, Royalty and this mod with the same error.  I removed Royalty and also got the same error.  So it definitely seems to be a problem in the mod.  If you're not getting it too, I am at a loss to explain what's happening.

Steps to reproduce: Configure the game to have the 3 or 4 mods I listed above enabled.  Start the game.  When the main menu loads, it will throw up the red error message in the console.
Let me know if there's anything else I can do to help assist in debugging this.  I know you're working for free here and I sincerely appreciate you taking the time to help me figure this out.

**Comment by firefoxpdm** [comment]
Okay, I have the error now. It seems something has changed in the core between 1.1.2570 and 1.1.2598 that is now causing this issue.

**Comment by firefoxpdm** [comment]
Github release done.

The core mod has added a new element in the original xml definition and the patching caused an invalid new structure. Luckily the fix was quite straightforward, and both the mining yield and speed seems to still be working fine.
